[project]
name = "client-python"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = [
    "lambda-otel-lite>=0.15.0",
    "opentelemetry-api>=1.32.1",
    "requests>=2.32.3",
]

[dependency-groups]
dev = [
    "ruff>=0.11.8",
]
